 ##  <center>Edyoda Data Wrangling Assignment </center>
### Assignment-1: NumPy

#### Name : Dineshkumar G
#### Batch : DS140821
#### Instructor : Shiva Reddy

#### Question 1:  Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
x = np.arange(10)==4
y = x*1
print(y)

[0 0 0 0 1 0 0 0 0 0]


#### Question 2:  Create a vector with values ranging from 10 to 49.

In [2]:
nums = np.arange(10,50)
print(nums)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Question 3:  Create a 3x3 matrix with values ranging from 0 to 8.

In [3]:
array2d = np.arange(start = 0, stop= 9 )
array2d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question 4:  Find indices of non-zero elements from [1,2,0,0,4,0].

In [10]:
new = np.array([1,2,0,0,4,0])
non_zero = new.nonzero()
print(non_zero)

(array([0, 1, 4], dtype=int64),)


#### Question 5:  Create a 10x10 array with random values and find the minimum and maximum values.

In [78]:
n = np.random.randint(low=1,high=101,size=(10,10))
max_n = n.max()
min_n = n.min()
print('Array is\n',x)
print('Max val:',max_n)
print('Min val:',min_n)

Array is
 [[99 51 14 76  9 65 32 24 28 53]
 [77 40 93 56 33 93 85  6 88 28]
 [33  8 20 17 82 63 60 43 40 79]
 [82 28 51 93 14 38 64 18 57 38]
 [ 2 65 61 89 28 70 10 30 50 67]
 [49 40 95 52 44 38 53 12 60 80]
 [59 62 85 24 54 13 96 64 95 38]
 [28 26 68 86 44  8 69 71 64 49]
 [44 11  8 62 13 57 56 41 33 49]
 [42 93 43 60  9  3 67 10 83 98]]
Max val: 99
Min val: 1


#### Question 6:  Create a random vector of size 30 and find the mean value.

In [81]:
m = np.random.random(30)
print('array is\n',m)
print('')
m.mean()

0.4671507489648093